### ISSUE TITLE
Issue: Missing e107_lgsl after install

### ISSUE THREAD

**Issue by LaocheXe** [Jimako-e107-plugins/lgsl#4]
Fatal error: Uncaught mysqli_sql_exception: Table '*****_testing.e107_lgsl' doesn't exist in /usr/www/*****/e107-test/e107_plugins/lgsl-main/lgsl_files/lgsl_admin.php:358

Get no error when installing. 

Bottom of the lgsl_sql.php is TYPE=MyISAM, when using that in the SQL - returns an error: #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TYPE=MyISAM' at line 15

Changing TYPE= to ENGINE should fix it

**Comment by Jimmi08** [comment]
Weird. Don't you know why it didn't happen to me?  Thank you for the fix, of course,

**Comment by LaocheXe** [comment]
Might be the version I believe - I use whatever NFOServers has me at, which is 5.7.41. Are you using MySQL Lite or something?

**Comment by Jimmi08** [comment]
Wampp installation... Server version: 8.0.31 - MySQL Community Server - GPL
