### ISSUE TITLE
Seems a lot is broken in release 6.2.1

### ISSUE THREAD

**Issue by UG-Asger** [Jimako-e107-plugins/lgsl#9]
Paths to eg. levelshots
Zones not working
Locations not working

![image](https://github.com/user-attachments/assets/9466ab10-f2b3-4544-999f-61e9ed1d9b58)

**Comment by UG-Asger** [comment]
![image](https://github.com/user-attachments/assets/abddb7ac-2a67-4fc6-9fb2-cdb307802cb2)

**Comment by Jimmi08** [comment]
Did you check all your settings?

Dňa po, 19. aug 2024, 17:43 Asger ***@***.***> napísal(a):

**Comment by UG-Asger** [comment]
Yep and also tried to add real path, without luck
![image](https://github.com/user-attachments/assets/90c8c709-7f5e-4aba-8918-08798df096d5)

**Comment by UG-Asger** [comment]
Maybe it would be easier to go for 7.0.0 RC now, instead of spending a lot of time on the old release?

**Comment by UG-Asger** [comment]
You have full access to the files on my server for the SA version (placed in folder lgsl7). You can check if that would be easier to integrate

**Comment by Jimmi08** [comment]
> Maybe it would be easier to go for 7.0.0 RC now, instead of spending a lot of time on fixing the old release?

No, it would be harder to detect problem.  Now it is only PHP 8 or e107 itself (lgsl config file)

**Comment by UG-Asger** [comment]
Tried to message you on Discord :) But couldn't :) Please accept my friend request, so that we can communicate there

**Comment by Jimmi08** [comment]
> ![image](https://private-user-images.githubusercontent.com/68121399/359162485-abddb7ac-2a67-4fc6-9fb2-cdb307802cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODM3MTgsIm5iZiI6MTcyNDA4MzQxOCwicGF0aCI6Ii82ODEyMTM5OS8zNTkxNjI0ODUtYWJkZGI3YWMtMmE2Ny00ZmM2LTlmYjItY2RiMzA3ODAyY2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE2MDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYTIxOGI2MWI0N2U0MTdmMTM5Y2Y3M2U0ZmVjYjgyYmEzOGJkYTEwYWE3MzQwM2VlY2UyNTI0NjVkYWRmN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H-9n6bhhIIZ2hCuJtR0k_MFljqqHi5CHWfqPKGj1mNg)

Fixed.  Please create one issue for one problem.

**Comment by UG-Asger** [comment]
Oki. Cant see the image though, but i beleive it was this that "e107 Menu items area 1/2 broken" that you fixed
